services:
  expenses:
    build: .
    container_name: expenses
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - STORAGE_URL=/app/data
    restart: unless-stopped
